# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir X:/EC551/EC551_Final_Project/FInal_Project/FInal_Project.cache/wt [current_project]
set_property parent.project_path X:/EC551/EC551_Final_Project/FInal_Project/FInal_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo x:/EC551/EC551_Final_Project/FInal_Project/FInal_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  X:/EC551/EC551_Final_Project/KeyboardInputAndTiming/KeyboardInputAndTiming/ANoteClkDivider.v
  X:/EC551/EC551_Final_Project/FInal_Project/FInal_Project.srcs/sources_1/new/Clock_Divider.v
  X:/EC551/EC551_Final_Project/FInal_Project/FInal_Project.srcs/sources_1/new/Duty_Cycler.v
  X:/EC551/EC551_Final_Project/KeyboardInputAndTiming/KeyboardInputAndTiming/KeyboardClkDivider.v
  X:/EC551/EC551_Final_Project/KeyboardInputAndTiming/KeyboardInputAndTiming/LongClkDivider.v
  X:/EC551/EC551_Final_Project/KeyboardInputAndTiming/KeyboardInputAndTiming/NoteDurationClkDivider.v
  X:/EC551/EC551_Final_Project/KeyboardInputAndTiming/KeyboardInputAndTiming/PS2Receiver.v
  X:/EC551/EC551_Final_Project/FInal_Project/FInal_Project.srcs/sources_1/new/Sine_Gen.v
  X:/EC551/EC551_Final_Project/KeyboardInputAndTiming/KeyboardInputAndTiming/debouncer.v
  X:/EC551/EC551_Final_Project/KeyboardInputAndTiming/KeyboardInputAndTiming/Synthesizer.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc X:/EC551/EC551_Final_Project/FInal_Project/FInal_Project.srcs/constrs_1/new/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files X:/EC551/EC551_Final_Project/FInal_Project/FInal_Project.srcs/constrs_1/new/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Synthesizer -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Synthesizer.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Synthesizer_utilization_synth.rpt -pb Synthesizer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
